# Generated by Django 4.2.13 on 2024-06-07 10:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0006_rename_description_todoitem_content_todoitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='original_url',
            field=models.URLField(default=datetime.datetime(2024, 6, 7, 10, 42, 9, 775658, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='related_site_url',
            field=models.URLField(default=datetime.datetime(2024, 6, 7, 10, 42, 21, 676193, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 6, 7, 10, 42, 32, 623679, tzinfo=datetime.timezone.utc), upload_to='todos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
