# Generated by Django 5.0.6 on 2024-06-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_alter_todoitem_content_alter_todoitem_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='original_url',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='related_site_url',
        ),
    ]
