# Generated by Django 4.2.13 on 2024-06-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_alter_todoitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
