# Generated by Django 5.0.6 on 2024-06-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_todoitem_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='project',
            field=models.TextField(blank=True),
        ),
    ]
